version: 0
metadata:
  name: testBed
  description: Automated Tests
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    priority: lowest
    retries: 5
#    routes:
#           - 'notify.email.<roxana.robotin@softvision.ro>.on-any'
    extra:
      github:
        events:
          - push
          - pull_request.opened
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: rrobotin/testbed_linux:4
      artifacts:
         public/results:
           path: /repo/reports
           type: directory
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          whoami &&
          git --version &&
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          npm install . &&
          pwd &&
          mkdir reports &&
          ls -all &&
          apt-get update &&
          node runTest.js &&
          node processReportInput.js &&
          cp createReportPage.js reports/ &&
          cp webRTCreports.html reports/ &&
          cp -r images/ reports/ &&
          cd reports &&
          ls -all
    metadata:
      name: 'testBed'
      description: 'Automated video/audio tests '
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
