version: 0
metadata:
  name: testBed
  description: Automated Tests
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    priority: lowest
    retries: 5
#    routes:
#           - 'notify.email.<roxana.robotin@softvision.ro>.on-any'
    extra:
      github:
        events:
          - push
          - pull_request.opened
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: rrobotin/testbed_linux:3
      artifacts:
         public/results:
           path: /repo/roxana
           type: directory
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          whoami &&
          git --version &&
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          npm install . &&
          pwd &&
          wget http://archive.mozilla.org/pub/firefox/nightly/latest-date/firefox-56.0a1.en-US.linux-x86_64.tar.bz2 &&
          ls -latr &&
          tar xjvf  firefox-56.0a1.en-US.linux-x86_64.tar.bz2 &&
          ls -latr &&
          echo $PATH &&
          $PATH=$PATH:/repo/firefox &&
          echo $PATH &&
          pwd &&
          mkdir roxana &&
          cd roxana &&
          touch test.txt &&
          cd ../ &&
          echo "whereis firefox" &&
          whereis firefox &&
          echo "whereis browsers" &&
          whereis browsers &&
          echo "install FF" &&
          apt-get update &&
          echo "whereis firefox part II" &&
          whereis firefox &&
          node runTest.js &&
          node formatResults.js
    metadata:
      name: 'testBed'
      description: 'Automated video/audio tests '
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
